/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetobanco;

import java.io.IOException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Arthur
 */
public class tInicio extends javax.swing.JFrame {

    /**
     * Creates new form tInicio
     */
    public tInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jB1 = new javax.swing.JButton();
        JogoSalvo = new javax.swing.JButton();
        jB3 = new javax.swing.JButton();
        jB4 = new javax.swing.JButton();
        jL1 = new javax.swing.JLabel();
        Fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(580, 380));
        setMinimumSize(new java.awt.Dimension(580, 380));
        setPreferredSize(new java.awt.Dimension(580, 380));
        setResizable(false);
        setSize(new java.awt.Dimension(580, 380));
        getContentPane().setLayout(null);

        jB1.setFont(new java.awt.Font("SF Distant Galaxy Alternate", 2, 14)); // NOI18N
        jB1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FButton.jpg"))); // NOI18N
        jB1.setText("Iniciar Jogo");
        jB1.setBorder(new javax.swing.border.SoftBevelBorder(0));
        jB1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jB1.setMaximumSize(new java.awt.Dimension(50, 20));
        jB1.setMinimumSize(new java.awt.Dimension(50, 20));
        jB1.setPreferredSize(new java.awt.Dimension(50, 20));
        jB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB1ActionPerformed(evt);
            }
        });
        getContentPane().add(jB1);
        jB1.setBounds(110, 110, 120, 20);

        JogoSalvo.setFont(new java.awt.Font("SF Distant Galaxy Alternate", 2, 14)); // NOI18N
        JogoSalvo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FButton.jpg"))); // NOI18N
        JogoSalvo.setText("Jogo Salvo");
        JogoSalvo.setBorder(new javax.swing.border.SoftBevelBorder(0));
        JogoSalvo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JogoSalvo.setMaximumSize(new java.awt.Dimension(50, 20));
        JogoSalvo.setMinimumSize(new java.awt.Dimension(50, 20));
        JogoSalvo.setPreferredSize(new java.awt.Dimension(50, 20));
        JogoSalvo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JogoSalvoActionPerformed(evt);
            }
        });
        getContentPane().add(JogoSalvo);
        JogoSalvo.setBounds(110, 150, 120, 20);

        jB3.setFont(new java.awt.Font("SF Distant Galaxy Alternate", 2, 14)); // NOI18N
        jB3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FButton.jpg"))); // NOI18N
        jB3.setText("Ajuda");
        jB3.setBorder(new javax.swing.border.SoftBevelBorder(0));
        jB3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jB3.setMaximumSize(new java.awt.Dimension(50, 20));
        jB3.setMinimumSize(new java.awt.Dimension(50, 20));
        jB3.setPreferredSize(new java.awt.Dimension(50, 20));
        jB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB3ActionPerformed(evt);
            }
        });
        getContentPane().add(jB3);
        jB3.setBounds(110, 190, 120, 20);

        jB4.setFont(new java.awt.Font("SF Distant Galaxy Alternate", 2, 14)); // NOI18N
        jB4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FButton.jpg"))); // NOI18N
        jB4.setText("Sair");
        jB4.setBorder(new javax.swing.border.SoftBevelBorder(0));
        jB4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jB4.setMaximumSize(new java.awt.Dimension(50, 20));
        jB4.setMinimumSize(new java.awt.Dimension(50, 20));
        jB4.setPreferredSize(new java.awt.Dimension(50, 20));
        jB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB4ActionPerformed(evt);
            }
        });
        getContentPane().add(jB4);
        jB4.setBounds(110, 230, 120, 20);

        jL1.setFont(new java.awt.Font("MV Boli", 1, 36)); // NOI18N
        jL1.setText("IFAL Simulator");
        getContentPane().add(jL1);
        jL1.setBounds(50, 30, 300, 40);

        Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fInicio.jpg"))); // NOI18N
        getContentPane().add(Fundo);
        Fundo.setBounds(-250, 0, 890, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB1ActionPerformed
        tAtribs tela1 = new tAtribs();
        tela1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jB1ActionPerformed

    private void JogoSalvoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JogoSalvoActionPerformed
        //Aqui tu vai botar o jogo salvo , se liga vou deixar um parte pronta
        
        PersonPrincipal personTemp = new PersonPrincipal();
        ArrayList<Professor> professores = new ArrayList();
        ArrayList<Materia> temp1 = new ArrayList();
        Tempo tempoTemp = new Tempo();
        tOpcoes tela = new tOpcoes();
        FuncoesBanco DAO = new FuncoesBanco();
        for(int i = 0 ; i <15 ; i ++){
            Professor Temp = new  Professor();
            Temp.Nome = (DAO.nomePf(i+1));
            Temp.afetividade = DAO.afetoPf(i+1);
            Temp.desafeto = DAO.desafetoPf(i+1);
            professores.add(Temp);
        }
        tOpcoes t1 = new tOpcoes();
        try {
            t1.definirMaterias();
        } catch (IOException ex) {
            Logger.getLogger(tInicio.class.getName()).log(Level.SEVERE, null, ex);
        }
        for(int i = 0 ; i <15 ; i ++){
            Materia temp = t1.p.Materias.get(i);
            temp.Notasbimestrais[0] = (float) DAO.notab1M(i+1);
            temp.Notasbimestrais[1] = (float) DAO.notab2M(i+1);
            temp.Notasbimestrais[2] = (float) DAO.notab3M(i+1);
            temp.Notasbimestrais[3] = (float) DAO.notab4M(i+1);
            temp.faltas = DAO.faltasM(i+1);
            temp.professor = professores.get(i);
            temp.Nome = t1.p.Materias.get(i).Nome;
            temp1.add(temp);
        }
        personTemp.Materias = temp1;
        DateFormat df = new SimpleDateFormat ("dd/MM/yyyy");
        try {
            //infos do tempo
            tempoTemp.recolocar(DAO.data_atualT(),DAO.dia_semanaT(), DAO.bimestreT());
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null,"vrau");
        } catch (IOException ex) {
            Logger.getLogger(tInicio.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //infos do personagem
        personTemp.Finança = DAO.financaP();
        personTemp.Humor = DAO.humorP();
        personTemp.Inteligencia = DAO.inteligenciaP();
        personTemp.Nome = DAO.nomeP();
        personTemp.carisma = DAO.carismaP();
        personTemp.money = (float) DAO.dinheiroP();
        personTemp.horasEstudadas = DAO.horasP();
        
        tela.recuperarInfos(tempoTemp, personTemp);
        JOptionPane.showMessageDialog(null,"Carregado Com Sucesso");
        this.setVisible(false);
        tela.setVisible(true);
        
        //dps vc chama esse metodo tela.recuperarInfos() , vc passa como parametro as 2 temporarias dps de instanciar <3
        // relembrando pra n mecher nos nomes das variaveis da tela
        
    }//GEN-LAST:event_JogoSalvoActionPerformed

    private void jB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB3ActionPerformed
        JOptionPane.showMessageDialog(null,"Primeiramente Calouro não tem vez\nSegundamente se vira , pois calouro não tem vez");
    }//GEN-LAST:event_jB3ActionPerformed

    private void jB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jB4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fundo;
    private javax.swing.JButton JogoSalvo;
    private javax.swing.JButton jB1;
    private javax.swing.JButton jB3;
    private javax.swing.JButton jB4;
    private javax.swing.JLabel jL1;
    // End of variables declaration//GEN-END:variables
}
